/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_chungles_frameworks_stateless_StatelessNativeLibraryLoader */

#ifndef _Included_org_chungles_frameworks_stateless_StatelessNativeLibraryLoader
#define _Included_org_chungles_frameworks_stateless_StatelessNativeLibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_chungles_frameworks_stateless_StatelessNativeLibraryLoader
 * Method:    addApplication
 * Signature: (Ljava/lang/String;)Lorg/chungles/frameworks/stateless/StatelessApplication;
 */
JNIEXPORT jobject JNICALL Java_org_chungles_frameworks_stateless_StatelessNativeLibraryLoader_addApplication
  (JNIEnv *, jobject, jstring);
/*
 * Class:     org_chungles_frameworks_stateless_StatelessNativeApplication
 * Method:    ngetAppID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_chungles_frameworks_stateless_StatelessNativeApplication_ngetAppID
  (JNIEnv *, jobject);

/*
 * Class:     org_chungles_frameworks_stateless_StatelessNativeApplication
 * Method:    ngetSystemCommand
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_chungles_frameworks_stateless_StatelessNativeApplication_ngetSystemCommand
  (JNIEnv *, jobject);

/*
 * Class:     org_chungles_frameworks_stateless_StatelessNativeApplication
 * Method:    nfreeze
 * Signature: ()Lorg/chungles/frameworks/stateless/State;
 */
JNIEXPORT jobject JNICALL Java_org_chungles_frameworks_stateless_StatelessNativeApplication_nfreeze
  (JNIEnv *, jobject);

/*
 * Class:     org_chungles_frameworks_stateless_StatelessNativeApplication
 * Method:    nthaw
 * Signature: (Lorg/chungles/frameworks/stateless/State;)V
 */
JNIEXPORT void JNICALL Java_org_chungles_frameworks_stateless_StatelessNativeApplication_nthaw
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_chungles_frameworks_stateless_StatelessNativeApplication
 * Method:    nhasEnoughMemory
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_chungles_frameworks_stateless_StatelessNativeApplication_nhasEnoughMemory
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
